In [1]:
import numpy as np
import glob

In [2]:
logs = glob.glob("Players_Data_teach_ingestion/*.npy")

In [3]:
ingested = []
ingested_successfully = []

for log in logs:
    logdata = np.load(log, allow_pickle=True)
    for logval in logdata:
        if len(logval) > 2 and logval[0] == 9:
            ingested.append(log)
            if logval[2] == 100:
                ingested_successfully.append(log)
                
ingested = list(set(ingested))
ingested_successfully = list(set(ingested_successfully))

In [4]:
len(ingested), len(ingested_successfully)

(417, 97)

In [5]:
ingested_successfully = sorted(ingested_successfully, key=lambda x: int(x.split("/")[1].split("-")[0]))

In [6]:
ingested_successfully

['Players_Data_teach_ingestion/0-7.npy',
 'Players_Data_teach_ingestion/18-10.npy',
 'Players_Data_teach_ingestion/19-17.npy',
 'Players_Data_teach_ingestion/19-18.npy',
 'Players_Data_teach_ingestion/19-19.npy',
 'Players_Data_teach_ingestion/38-33.npy',
 'Players_Data_teach_ingestion/39-42.npy',
 'Players_Data_teach_ingestion/41-47.npy',
 'Players_Data_teach_ingestion/41-45.npy',
 'Players_Data_teach_ingestion/41-50.npy',
 'Players_Data_teach_ingestion/42-55.npy',
 'Players_Data_teach_ingestion/43-61.npy',
 'Players_Data_teach_ingestion/43-60.npy',
 'Players_Data_teach_ingestion/44-70.npy',
 'Players_Data_teach_ingestion/47-88.npy',
 'Players_Data_teach_ingestion/48-101.npy',
 'Players_Data_teach_ingestion/48-107.npy',
 'Players_Data_teach_ingestion/49-120.npy',
 'Players_Data_teach_ingestion/49-128.npy',
 'Players_Data_teach_ingestion/49-139.npy',
 'Players_Data_teach_ingestion/49-119.npy',
 'Players_Data_teach_ingestion/50-151.npy',
 'Players_Data_teach_ingestion/50-159.npy',
 'Pla

In [8]:
log = np.load("Players_Data_teach_ingestion/100-912.npy", allow_pickle=True)

for x in log:
    print(x)

[240, 572]
[746  89]
[10 101 -50 199 -1 array(-1) 240 572
 array([array([-47, -59, -9, -15], dtype=object),
       array([-27, 81, 1, -57, 32, 2, 78, 57, 2, 75, -43, 2, 32, 79, 1, 40, 88,
       1], dtype=object)], dtype=object)]
[10 102 -50 198 -1 array(-1) 240 572
 array([array([-47, -59, -9, -15], dtype=object),
       array([-27, 81, 1, -59.12132034355966, 34.12132034355966, 2, 75, -43, 2,
       32, 79, 1, 40, 88, 1, -55, 39, 1, 60, 7, 1], dtype=object)],
      dtype=object)]
[12 103 -50 197 -1 240 572
 array([array([-47, -59, -9, -15], dtype=object),
       array([-27, 81, 1, -59.12132034355966, 34.12132034355966, 2, 75, -43, 2,
       40, 88, 1, -55, 39, 1, 60, 7, 1, -89, -13, 2], dtype=object)],
      dtype=object)]
[10 104 -50 196 -1 array(-1) 240 572
 array([array([-47, -59, -9, -15], dtype=object),
       array([-29.12132034355966, 83.12132034355966, 1, -56.12132034355966,
       34.12132034355966, 2, 75, -43, 2, 40, 88, 1, 60, 7, 1, -47, 86, 1,
       85, -36, 1, 33, -62, 2