In [1]:
import numpy as np
import os

In [2]:
path = "Players_Data_test_state_10k"

In [16]:
def study(filename):
    global path
    
    logs = np.load(os.path.join(path, filename), allow_pickle=True)
    
    for log in logs:
        if(len(log) > 2):
            print("Time:", log[1], end=" -> ")
        print(log)
        print()

In [17]:
study("52-39.npy")

[888, 318]

[19 42]

Time: 53 -> [10 53 -20 199 -1 array(-1) 888 318
 array([array([-25, -95, -32, -56], dtype=object),
       array([55, -65, 1], dtype=object)], dtype=object)]

Time: 54 -> [10 54 -20 198 -1 array(-1) 888 318
 array([array([-25, -95, -32, -56], dtype=object),
       array([55, -65, 1], dtype=object)], dtype=object)]

Time: 55 -> [10 55 -20 197 -1 array(-1) 888 318
 array([array([-25, -95, -32, -56], dtype=object),
       array([55, -65, 1], dtype=object)], dtype=object)]

Time: 56 -> [10 56 -20 196 -1 array(-1) 888 318
 array([array([-25, -95, -32, -56], dtype=object),
       array([55, -65, 1], dtype=object)], dtype=object)]

Time: 57 -> [10 57 -20 195 -1 array(-1) 888 318
 array([array([-25, -95, -32, -56], dtype=object),
       array([55, -65, 1], dtype=object)], dtype=object)]

Time: 58 -> [10 58 -20 194 -1 array(-1) 888 318
 array([array([-25, -95, -32, -56], dtype=object),
       array([55, -65, 1], dtype=object)], dtype=object)]

Time: 59 -> [10 59 -20 193 -1 a

# 